CREATE TABLE `subconsultas`.`pedidos` (`Identificador` INT(255) NOT NULL AUTO_INCREMENT , `clientes_id` INT(255) NOT NULL , `fecha` DATE NOT NULL , `total` INT(255) NOT NULL , PRIMARY KEY (`Identificador`)) ENGINE = InnoDB;


AQUI DEJAMOS EL VALOS DE CIELNTES_ID EN INT PARA PODER RELACIONARLOS DESPUES CON LA TABLA CLIENTES CON EL IDENTIFICADOR.